----首先删除相关配置
DELETE FROM TB_HRTMPSE where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPE where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPSA where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPAR where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPA where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPSD where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPSG where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPRD where TID = 'VACATIONPARAM'
DELETE FROM TB_HR_USERROLE where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPR where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPD where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPG where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPS where TID = 'VACATIONPARAM'
DELETE FROM TB_HRTMPH where TID = 'VACATIONPARAM'


--模板定义表的配置
INSERT INTO TB_HRTMPH( TID,TDESC,TDESCCHS,TCRTDATE,TREC,BTNSTANTION,ROLEFILE,BISSTOP) VALUES ('VACATIONPARAM','Params for staff vacation','假期管理参数配置','2011/11/24 14:29:01','1','2','','0')
--模板分组表的配置
----模板分组1的配置
INSERT INTO TB_HRTMPG( TID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GHIST,GPAGE,GRCOUNT,GVIEW,GSQL,USERPAGE,islarge) VALUES ('VACATIONPARAM','1','Main','主信息','0','','1','','','0','0','','0','','','0')
----模板分组1下各表字段属性的配置
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','1','isStop','Is Stopped','是否停用','varchar','1','0','0','2','0','1','BOOL','','60','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','1','label','Label','标签','varchar','50','0','1','','0','0','','','40','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','1','paramDesc','Param Description','参数描述','varchar','1000','0','1','','0','3','','','30','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','1','paramName','Param name','参数名称','varchar','50','0','0','','1','0','','','10','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','1','paramValue','Param Value','参数值','varchar','100','0','0','','0','0','','','20','0','0','1','50','','','','','','0')
--模板状态场景表的配置
----模板状态场景Maintain的配置
INSERT INTO TB_HRTMPS (TID,SID,SDESC,SDESCCHS,SSLCT,SREF,SADD,SDEL,SEDIT,SALERT,SORDER,SSIZE,SCFORM,Filter) VALUES ('VACATIONPARAM','Maintain','Maintain','维护','','','1','1','1','0','','2','0','')
----模板场景状态Maintain下分组表的配置
INSERT INTO TB_HRTMPSG( TID,SID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GRIGHT,GSLCT,GPAGE,GRCOUNT,DEFAULTCOLUMN,USERPAGE,islarge) VALUES ('VACATIONPARAM','Maintain','1','Main','主信息','0','','1','','','7','','0','','0','','0')
------模板场景状态Maintain下分组1表的配置
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','Maintain','1','isStop','Is Stopped','是否停用','varchar','1','0','0','2','0','1','BOOL','','60','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','Maintain','1','label','Label','标签','varchar','50','0','1','','0','0','','','40','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','Maintain','1','paramDesc','Param Description','参数描述','varchar','1000','0','1','','0','3','','','30','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','Maintain','1','paramName','Param name','参数名称','varchar','50','0','0','','1','0','','','10','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATIONPARAM','Maintain','1','paramValue','Param Value','参数值','varchar','100','0','0','','0','0','','','20','0','0','1','50','','','','','','0')
--模板角色表的配置
----模板角色Manager的配置
INSERT INTO TB_HRTMPR ( TID,RID,RDESC,RDESCCHS,RPARA0,RPARA1,RPARA2,RPARA3,RPARA4,RPARA5,RPARA6,RPARA7,RPARA8,RPARA9,RORDER) VALUES ('VACATIONPARAM','Manager','Manager','管理员','','','','','','','','','','','1')
----模板角色Manager下角色状态的配置
INSERT INTO TB_HRTMPRD ( TID,RID,SID) VALUES ('VACATIONPARAM','Manager','Maintain')


