----首先删除相关配置
DELETE FROM TB_HRTMPSE where TID = 'VACATYPE'
DELETE FROM TB_HRTMPE where TID = 'VACATYPE'
DELETE FROM TB_HRTMPSA where TID = 'VACATYPE'
DELETE FROM TB_HRTMPAR where TID = 'VACATYPE'
DELETE FROM TB_HRTMPA where TID = 'VACATYPE'
DELETE FROM TB_HRTMPSD where TID = 'VACATYPE'
DELETE FROM TB_HRTMPSG where TID = 'VACATYPE'
DELETE FROM TB_HRTMPRD where TID = 'VACATYPE'
DELETE FROM TB_HR_USERROLE where TID = 'VACATYPE'
DELETE FROM TB_HRTMPR where TID = 'VACATYPE'
DELETE FROM TB_HRTMPD where TID = 'VACATYPE'
DELETE FROM TB_HRTMPG where TID = 'VACATYPE'
DELETE FROM TB_HRTMPS where TID = 'VACATYPE'
DELETE FROM TB_HRTMPH where TID = 'VACATYPE'


--模板定义表的配置
INSERT INTO TB_HRTMPH( TID,TDESC,TDESCCHS,TCRTDATE,TREC,BTNSTANTION,ROLEFILE,BISSTOP) VALUES ('VACATYPE','Type of Vacation','假期类型','2011/11/21 12:19:31','1','2','','0')
--模板分组表的配置
----模板分组1的配置
INSERT INTO TB_HRTMPG( TID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GHIST,GPAGE,GRCOUNT,GVIEW,GSQL,USERPAGE,islarge) VALUES ('VACATYPE','1','Main','主信息','0','1','1','','','0','0','','0','','','0')
----模板分组1下各表字段属性的配置
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','ISPAY','Is Pay','是否带薪','varchar','50','0','0','2','0','1','BOOL','','40','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','ISUSE','Is Use','是否在用','varchar','50','0','0','1','0','1','BOOL','','100','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','REMARK','Remark','备注','varchar','8000','0','1','','0','3','','','200','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','VTCODE','Type Code','假期类型编码','varchar','50','0','0','','1','0','','','10','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','VTNAME','Type Name','假期英文名','varchar','50','0','1','','0','0','','','20','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','1','VTNAMECN','Type Chinese Name','假期中文名','varchar','50','0','0','','0','0','','','30','0','0','1','50','','','','','','0')
--模板状态场景表的配置
----模板状态场景Maintain的配置
INSERT INTO TB_HRTMPS (TID,SID,SDESC,SDESCCHS,SSLCT,SREF,SADD,SDEL,SEDIT,SALERT,SORDER,SSIZE,SCFORM,Filter) VALUES ('VACATYPE','Maintain','Maintain','维护','','','1','1','1','0','','2','0','')
----模板场景状态Maintain下分组表的配置
INSERT INTO TB_HRTMPSG( TID,SID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GRIGHT,GSLCT,GPAGE,GRCOUNT,DEFAULTCOLUMN,USERPAGE,islarge) VALUES ('VACATYPE','Maintain','1','Main','主信息','0','1','1','','','7','','0','','0','','0')
------模板场景状态Maintain下分组1表的配置
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','ISPAY','Is Pay','是否带薪','varchar','50','0','0','2','0','1','BOOL','','40','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','ISUSE','Is Use','是否在用','varchar','50','0','0','1','0','1','BOOL','','100','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','REMARK','Remark','备注','varchar','8000','0','1','','0','3','','','200','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','VTCODE','Type Code','假期类型编码','varchar','50','0','0','','1','0','','','10','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','VTNAME','Type Name','假期英文名','varchar','50','0','1','','0','0','','','20','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','Maintain','1','VTNAMECN','Type Chinese Name','假期中文名','varchar','50','0','0','','0','0','','','30','0','0','1','50','','','','','','0')
----模板状态场景View的配置
INSERT INTO TB_HRTMPS (TID,SID,SDESC,SDESCCHS,SSLCT,SREF,SADD,SDEL,SEDIT,SALERT,SORDER,SSIZE,SCFORM,Filter) VALUES ('VACATYPE','View','View','查看','','','0','0','0','0','','2','0','')
----模板场景状态View下分组表的配置
INSERT INTO TB_HRTMPSG( TID,SID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GRIGHT,GSLCT,GPAGE,GRCOUNT,DEFAULTCOLUMN,USERPAGE,islarge) VALUES ('VACATYPE','View','1','Main','主信息','0','1','1','','','0','','0','','0','','0')
------模板场景状态View下分组1表的配置
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','ISPAY','Is Pay','是否带薪','varchar','50','0','0','2','0','1','BOOL','','40','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','ISUSE','Is Use','是否在用','varchar','50','0','0','1','0','1','BOOL','','100','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','REMARK','Remark','备注','varchar','8000','0','1','','0','3','','','200','0','0','0','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','VTCODE','Type Code','假期类型编码','varchar','50','0','0','','1','0','','','10','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','VTNAME','Type Name','假期英文名','varchar','50','0','1','','0','0','','','20','0','0','1','50','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('VACATYPE','View','1','VTNAMECN','Type Chinese Name','假期中文名','varchar','50','0','0','','0','0','','','30','0','0','1','50','','','','','','0')
--模板角色表的配置
----模板角色Manager的配置
INSERT INTO TB_HRTMPR ( TID,RID,RDESC,RDESCCHS,RPARA0,RPARA1,RPARA2,RPARA3,RPARA4,RPARA5,RPARA6,RPARA7,RPARA8,RPARA9,RORDER) VALUES ('VACATYPE','Manager','Manager','管理员','','','','','','','','','','','2')
----模板角色Manager下角色状态的配置
INSERT INTO TB_HRTMPRD ( TID,RID,SID) VALUES ('VACATYPE','Manager','Maintain')
----模板角色Viewer的配置
INSERT INTO TB_HRTMPR ( TID,RID,RDESC,RDESCCHS,RPARA0,RPARA1,RPARA2,RPARA3,RPARA4,RPARA5,RPARA6,RPARA7,RPARA8,RPARA9,RORDER) VALUES ('VACATYPE','Viewer','Viewer','查看员','','','','','','','','','','','1')
----模板角色Viewer下角色状态的配置
INSERT INTO TB_HRTMPRD ( TID,RID,SID) VALUES ('VACATYPE','Viewer','View')


