/*==============================================================*/
/* 在系统模板中增加一个模板，命名为：SQLLOG                     */
/* 其具体结构为：                                               */
/*==============================================================*/


 /*   SLOGID               varchar(40)          not null,=======*/
 /*   SUSERID              varchar(40)          null,=======*/
 /*   SUSERNAME            varchar(40)          null,=======*/
 /*   SUSERNAMECN          varchar(40)          null,=======*/
 /*   DTOPTIME             datetime             null,=======*/
 /*   SIP                  varchar(100)         null,=======*/
 /*   SSQL                 varchar(8000)        null,=======*/
 /*   BISSUCCESS           char(1)              null,=======*/
   
/*==============================================================*/
/* 该模板将记录通过页面ExecuteSql.aspx执行SQL的操作日志         */
/* 该模板仅仅只是进行日志的查看                                 */
/*==============================================================*/

--模板定义表的配置
INSERT INTO TB_HRTMPH( TID,TDESC,TDESCCHS,TCRTDATE,TREC,BTNSTANTION,ROLEFILE,BISSTOP) VALUES ('SQLLOG','Log For Excute Sql','执行SQL的记录日志','2011/9/10 22:04:39','1','2','','0')
--模板分组表的配置
----模板分组1的配置
INSERT INTO TB_HRTMPG( TID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GHIST,GPAGE,GRCOUNT,GVIEW,GSQL,USERPAGE,islarge) VALUES ('SQLLOG','1','Main','主信息','0','1','1','','','0','0','','0','','','0')
----模板分组1下各表字段属性的配置
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','BISSUCCESS','Is Success','是否成功','varchar','10','0','0','','0','0','','','80','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','DTOPTIME','Excute Time','操作时间','datetime','50','0','0','','0','0','','','50','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SIP','Excute IP','操作IP','varchar','50','0','0','','0','0','','','60','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SLOGID','log ID','编码序号','varchar','50','0','0','','1','0','','','10','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SSQL','Excute SQL','执行语句','varchar','8000','0','0','','0','3','','','70','0','0','0','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SUSERID','UserId','用户编码','varchar','50','0','0','','0','0','','','20','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SUSERNAME','User English Name','用户英文名','varchar','50','0','1','','0','0','','','30','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPD( TID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','1','SUSERNAMECN','User Chinese Name','用户中文名','varchar','50','0','1','','0','0','','','40','0','0','1','100','','','','','','0')
--模板状态场景表的配置
----模板状态场景VIEW的配置
INSERT INTO TB_HRTMPS (TID,SID,SDESC,SDESCCHS,SSLCT,SREF,SADD,SDEL,SEDIT,SALERT,SORDER,SSIZE,SCFORM,Filter) VALUES ('SQLLOG','VIEW','VIEW LOG','查看日志','','','0','0','0','0','','2','0','')
----模板场景状态VIEW下分组表的配置
INSERT INTO TB_HRTMPSG( TID,SID,GID,GDESC,GDESCCHS,GTYPE,GORDER,GLIMIT,GCOUNT,GWIDTH,GRIGHT,GSLCT,GPAGE,GRCOUNT,DEFAULTCOLUMN,USERPAGE,islarge) VALUES ('SQLLOG','VIEW','1','Main','主信息','0','1','1','','','0','','0','','0','','0')
------模板场景状态VIEW下分组1表的配置
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','BISSUCCESS','Is Success','是否成功','varchar','10','0','0','','0','0','','','80','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','DTOPTIME','Excute Time','操作时间','datetime','50','0','0','','0','0','','','50','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SIP','Excute IP','操作IP','varchar','50','0','0','','0','0','','','60','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SLOGID','log ID','编码序号','varchar','50','0','0','','1','0','','','10','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SSQL','Excute SQL','执行语句','varchar','8000','0','0','','0','3','','','70','0','0','0','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SUSERID','UserId','用户编码','varchar','50','0','0','','0','0','','','20','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SUSERNAME','User English Name','用户英文名','varchar','50','0','1','','0','0','','','30','0','0','1','100','','','','','','0')
INSERT INTO TB_HRTMPSD( TID,SID,GID,PID,PDESC,PDESCCHS,PTYPE,PLEN,PPREC,PNULL,PDEFAULT,PISKEY,PCTRL,PCTRLID,PCTRLD,PORDER,PRIGHT,PSYS,PLIST,PWIDTH,PFONTL,PFONTC,PAGGR,PAGDEST,PMAST,PSAVE) VALUES ('SQLLOG','VIEW','1','SUSERNAMECN','User Chinese Name','用户中文名','varchar','50','0','1','','0','0','','','40','0','0','1','100','','','','','','0')
--模板角色表的配置
----模板角色view的配置
INSERT INTO TB_HRTMPR ( TID,RID,RDESC,RDESCCHS,RPARA0,RPARA1,RPARA2,RPARA3,RPARA4,RPARA5,RPARA6,RPARA7,RPARA8,RPARA9,RORDER) VALUES ('SQLLOG','view','viewer','查询员','','','','','','','','','','','1')
----模板角色view下角色状态的配置
INSERT INTO TB_HRTMPRD ( TID,RID,SID) VALUES ('SQLLOG','view','VIEW')
