set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
go




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<同步组织部门信息到树形表TB_HR_DEPT(部门信息表)中>
-- =============================================
ALTER PROCEDURE [dbo].[SP_InitDataToTB_HR_DEPT] 
	
AS
BEGIN
	--首先删除表中所有数据
	DELETE FROM TB_HR_DEPT

	DECLARE @LEVELID VARCHAR(20)--部门等级
	DECLARE @COUNT_LEVEL int--等级个数统计
	DECLARE @COUNT_LEVEL1 int--部门等级为最顶层的部门个数统计
	DECLARE @LEVEL_LEVEL1 int--部门等级为最顶层的部门等级编码
	set @COUNT_LEVEL = 0
	set @COUNT_LEVEL1 = 0
	set @LEVEL_LEVEL1 = ''
	
	--获取部门等级的集合填入游标
	DECLARE LEVEL_DS CURSOR FOR
	SELECT CID FROM TB_HRLSTD WHERE LID = 'DEPTLE' ORDER BY CID

	OPEN LEVEL_DS
	FETCH NEXT FROM LEVEL_DS INTO @LEVELID
	WHILE @@FETCH_STATUS=0
	BEGIN
		set @COUNT_LEVEL = @COUNT_LEVEL+1

			---根据部门等级获取部门信息集合
			DECLARE DEPT_DS CURSOR FOR
			SELECT OID,ODESC,ODESCCHS,OPID,OCOST FROM CSORGA_1 where OTEST = @LEVELID ORDER BY OID

			DECLARE @DEPTID VARCHAR(200)--部门ID
			DECLARE @DEPTNAME VARCHAR(200)--部门英文名
			DECLARE @DEPTNAMECN VARCHAR(200)--部门中文名
			DECLARE @PARENTID VARCHAR(200)--上级部门编码
			DECLARE @COSTCODE VARCHAR(200)--成本中心编码

			OPEN DEPT_DS
			FETCH NEXT FROM DEPT_DS INTO @DEPTID,@DEPTNAME,@DEPTNAMECN,@PARENTID,@COSTCODE
			WHILE @@FETCH_STATUS=0
			BEGIN
				--循环插入到部门表TB_HR_DEPT中
				insert into TB_HR_DEPT(SDEPTID,SDEPTNAME,SDEPTNAMECN,SPARENTDEPTID,SORDER,SLEVEL,SCOSTCODE,BISSTOP) 
					VALUES (@DEPTID,@DEPTNAME,@DEPTNAMECN,@PARENTID,'',@LEVELID,@COSTCODE,'0')

				--统计部门等级为最顶层的部门个数
				if @COUNT_LEVEL=1
				begin
					set @COUNT_LEVEL1 = @COUNT_LEVEL1 +1
					set @LEVEL_LEVEL1 = @LEVELID
				end

				FETCH NEXT FROM DEPT_DS INTO @DEPTID,@DEPTNAME,@DEPTNAMECN,@PARENTID,@COSTCODE

			END
			CLOSE DEPT_DS
			DEALLOCATE DEPT_DS

		FETCH NEXT FROM LEVEL_DS INTO @LEVELID

	END
	CLOSE LEVEL_DS
	DEALLOCATE LEVEL_DS
	
	PRINT @COUNT_LEVEL

	--如果部门等级为最顶层的部门个数为大于1时,则说明不存在酒店本身的根目录信息,则插入一条根目录
	IF 	@COUNT_LEVEL1>1
	BEGIN
		--循环插入到部门表TB_HR_DEPT中
		DECLARE @DEPTID_root VARCHAR(200)--部门ID
		DECLARE @DEPTNAME_root VARCHAR(200)--部门英文名
		DECLARE @DEPTNAMECN_root VARCHAR(200)--部门中文名

		SELECT @DEPTID_root=SMENUCODE,@DEPTNAME_root=SMENUNAME,@DEPTNAMECN_root=SMENUNAMECN FROM TB_HR_MENU WHERE SLEVEL = '0'
		SET @DEPTID_root = 'L0'+@DEPTID_root

		insert into TB_HR_DEPT(SDEPTID,SDEPTNAME,SDEPTNAMECN,SPARENTDEPTID,SORDER,SLEVEL,SCOSTCODE,BISSTOP) 
			VALUES (@DEPTID_root,@DEPTNAME_root,@DEPTNAMECN_root,NULL,'','0','','0')
		--同时更新次一级的上级编码
		update TB_HR_DEPT set SPARENTDEPTID = @DEPTID_root where SLEVEL = @LEVEL_LEVEL1
	END

END 



